name: Test

on: push
env:
  DCP_API_S3_HOST: ${{ secrets.DCP_API_S3_HOST }}
  DCP_API_S3_BUCKET: ${{ secrets.DCP_API_S3_BUCKET }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start Mosquitto
        uses: namoshek/mosquitto-github-action@v1

      - name: Test it
        run: |
          pipx install poetry
          poetry install
          poetry run pytest
